### ISSUE TITLE
Can not create Scratch Org with Person Account

### ISSUE THREAD

**Issue by anaimproove** [sfb2csolutionarchitects/b2c-crm-sync#101]
I am installing the connector and I am following the setup steps from the README.md file.
I want to use Person Accounts on my scratch org, so my .env file looks like the image below

![PersonAccount](https://user-images.githubusercontent.com/25003443/118860083-dcae8580-b8d2-11eb-9afa-34a201aeeee4.png)

But when I run the command `npm run crm-sync:sf:build`, it fails.
I get this error

![PersonAccount Error](https://user-images.githubusercontent.com/25003443/118860169-fb148100-b8d2-11eb-9470-1fd31ac65fcf.png)

I am using the last version of master branch (May 13). When in the .env file I set `SF_SCRATCHORGPROFILE=base`, the command `npm run crm-sync:sf:build` works fine and the scratch org is created. But with Person Account, the build command is not working.

**Comment by b2csolutionarchitect** [comment]
... hi @anaimproove -- thank you for creating this ticket.  Can you please post the json stacktrace and errors-array output to the screen on the deployment failure?  This usually has the specific reason the meta-data failed to be deployed.  If you could post the JSON vs. a screen-shot, that would make it easier to review what's going wrong.

The problem is specifically with the personaccount meta-data.  So, if you have a scratchOrg already deployed with the base meta-data, you can use the `sfdx force:source:deploy -p` command to deploy the personAccount meta-data.  The `-p` command expects the path to the meta-data being deployed.  This should work for you:

```bash
sfdx force:source:deploy -p "src/sfdc/person-accounts"
```

Please try that -- and then share the output generated by the failure message.  Once we see that, I'll have additional questions about what exists in your scratchOrg.  Thank you again for sharing your experience -- and please reach out if you need anything else.

**Comment by b2csolutionarchitect** [comment]
Ok -- perfect!  Thank you @anaimproove.  Here is the relevant error:

```json
        "data": [
            {
                "error": "SortOrder must be in sequential order from 1.",
                "fullName": "PersonAccount.Standard_Person_Account_Duplicate_Rule",
                "type": "DuplicateRule",
                "filePath": "src/sfdc/person-accounts/main/default/duplicateRules/PersonAccount.Standard_Person_Account_Duplicate_Rule.duplicateRule-meta.xml",
                "problemType": "Error",
                "height": 1
            }
        ]
```

This error is occurring because the sortOrder currently attached to your PersonAccount.Standard_Person_Account_Duplicate_Rule (defaulted to 1) isn't aligned with your scratchOrg configuration.  Here's what I'd like you to do:

- Log into your scratchOrg
- Open setup, and in the quick-find search for "dup" -- this should bring-up **Duplicate Rules** in the setup menu / navigation.
- Select **Duplicate Rules** from the setup menu so that the list of duplicateRules is displayed

> Take a screenshot of this list and post it to this this ticket.  I'd also like to know if this scratchOrg is build by a Developer Org, or from a custom DevHub for your customer / partner.

- Find the **PersonAccount.Standard_Person_Account_Duplicate_Rule** in the list of duplicate rules and view it.
- From the detail display, capture the sort-order that is visible.  

> You'll want to align the sortOrder in your source meta-data to the sortOrder that's present in your scratchOrg.  This is what's causing the error -- the sort order is incorrect, and SFDX / the Salesforce Platform doesn't allow that mismatch.  

Once that change is made, please try to re-deploy the PersonAcccount meta-data.  Let me know what your results are -- happy to support you, and appreciate your perseverance to get through the setup here.  This is super helpful for us, so thank you for your efforts.

**Comment by anaimproove** [comment]
Hi @b2csolutionarchitect.

Below you can find the screenshot of my scratch org **Duplicated Rules**.

![Scratch Org - Duplicated Rules](https://user-images.githubusercontent.com/25003443/119025154-c15b7d00-b99b-11eb-8d7b-0e3ee4abefe3.png)

My scratch org is from a custom DevHub.

I can not find the **PersonAccount.Standard_Person_Account_Duplicate_Rule** in the list.
There is a **Standard Account Duplicated Rule**, but I can not see any rule related to Person Accounts.

**Comment by b2csolutionarchitect** [comment]
Ok -- try this; remove the **PersonAccount.Standard_Person_Account_Duplicate_Rule** from your personAccount meta-data and try the deployment.  If it's not present, then let's not create what doesn't already exist (b2c-crm-sync is not dependent on this duplicateRule; we de-activate it assuming it exists and is present).

Let me know what results you have -- hopefully this unblocks you. :)

**Comment by anaimproove** [comment]
Hi @b2csolutionarchitect,

I removed the file `src/sfdc/person-accounts/main/default/duplicateRules/PersonAccount.Standard_Person_Account_Duplicate_Rule.duplicateRule-meta.xml` and then I run the command `sfdx force:source:deploy -p "src/sfdc/person-accounts"`, but I still get a failed deploy

![Deploy Error](https://user-images.githubusercontent.com/25003443/119239704-b000a500-bb42-11eb-81c8-e14be21ac852.png)

**Comment by b2csolutionarchitect** [comment]
Ok -- this looks like a different issue; it looks like your scratchOrg isn't setup for PersonAccounts.  Looking at the problem column, the personAccount recordType is missing from your scratchOrg.  Can you log into your scratchOrg `sfdx force:org:open` and verify that PersonAccounts is enabled?  You should see it from the objectManager.

**Comment by anaimproove** [comment]
I created the scratch org with base setup, because if in the .env file I set it as `personaccounts` the build command fails.

Previously you said

> So, if you have a scratchOrg already deployed with the base meta-data, you can use the sfdx force:source:deploy -p command to deploy the personAccount meta-data

I created the scratch org as base and then was expecting to deploy the personAccount metadata with the command `sfdx force:source:deploy -p "src/sfdc/person-accounts"`

I can not find the PersonAccount object listed in the objectManager of my scratch org.

**Comment by b2csolutionarchitect** [comment]
Ok -- so do this.  Remove the duplicateRule meta-data that I mentioned earlier, update your scratchOrg definition to use the `personaccounts` template, and try the build.  Let's troubleshoot the personAccounts flow to completion.  I think we're close.  Let me know what results you find, ok?

**Comment by anaimproove** [comment]
It worked! :) Thank you @b2csolutionarchitect. Now I can proceed with the setup.

**Comment by b2csolutionarchitect** [comment]
W00t!  Ok -- so first off THANK YOU!  Totally appreciate your perseverance.  Working through these issues is challenging sometimes.  It's easy to give up or walk away.  You didn't -- and one of the outcomes is we learned about an area where our install is fragile (specifically with the duplicateRules).  We need to harden this -- and we will. 

Second, feel good about this.  Complete the setup -- and let me know if you have any other questions.  Super happy to support you, ok?  Thank you again for your efforts, Ana.  Be proud. :)
