### ISSUE TITLE
DUPLICATE_VALUE: duplicate value found: B2C_Customer_ID__c duplicates value on record with id: 0035400000hDwBh

### ISSUE THREAD

**Issue by aelzayady** [sfb2csolutionarchitects/b2c-crm-sync#98]
This error happens while executing test case and reason is unknown

![Screenshot 2021-05-19 at 9 41 16 am](https://user-images.githubusercontent.com/39186028/118783191-bebb3380-b886-11eb-8573-a5c3b48812a0.png)
![Screenshot 2021-05-19 at 9 32 35 am](https://user-images.githubusercontent.com/39186028/118783201-c11d8d80-b886-11eb-9961-77d934572ffd.png)
![Screenshot 2021-05-19 at 9 31 57 am](https://user-images.githubusercontent.com/39186028/118783203-c1b62400-b886-11eb-800d-52cae1caebcb.png)

**Comment by b2csolutionarchitect** [comment]
@aelzayady -- what I recommend is reviewing the log-files generated by B2C Commerce to identify what is causing the 401 errors being reported by the unit tests.  If you enable debug-level logging in your B2C instance, b2c-crm-sync will generate log files for the integration cartridge and REST API calls made to the Salesforce Platform.  Here's what I do when I'm debugging unit tests:

- Delete the current instance of the error, customerror, debug, info, and warning log files.
- Ensure that custom logging is set at the debug log-level.
- Execute a sub-set of the multi-cloud unit tests -- and let the tests for a given suite complete.
- Examine the log file for failures to see what is specifically failing.

Sometimes, the sandboxes will choke on a REST API request -- other times, these failures are the result of an incomplete setup (ex. your scratchOrg may not have customerLists and sites configured or activated).  The log files will give you insight into why the tests are failing.  If you share your results, we can then support you getting your environment configured so that they perform as expected.

**Comment by b2csolutionarchitect** [comment]
... this issue was addressed by #104; closing.
